In [55]:
import pandas as pd

movies_csv= "movies.csv"

movie_df= pd.read_csv(movies_csv,sep="|")

C:\Users\duduc\AppData\Local\Temp\ipykernel_20784\3686742584.py:5: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  movie_df= pd.read_csv(movies_csv,sep="|")

In [56]:

movie_df = movie_df.drop_duplicates(['id'])
movie_df = movie_df[~movie_df.isin([r"\N"])]
movie_df= movie_df.dropna()
movie_df

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos,generoArtista,personagem,nomeArtista,anoNascimento,anoFalecimento,profissao,titulosMaisConhecidos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200,actress,Miss Geraldine Holbrook (Miss Jerry),Blanche Bayliss,1878,1951,actress,tt0000009
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,1908,120,"Adventure,Fantasy",5.2,66,actor,The Wizard of Oz Man,L. Frank Baum,1856,1919,"writer,producer,miscellaneous","tt0004207,tt0089908,tt0032138,tt0000679"
87,tt0001285,The Life of Moses,The Life of Moses,1909,50,"Biography,Drama,Family",5.5,58,actor,Moses,Pat Hartigan,1881,1951,"director,actor,producer","tt1308969,tt0010949,tt1320429,tt2489106"
124,tt0001614,The Four Devils,De fire djævle,1911,60,Drama,6.3,31,actor,Fritz,Robert Dinesen,1874,1972,"director,actor,writer","tt0001614,tt0473730,tt0015107,tt0129092"
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,1913,60,Drama,6.2,49,actress,Éponine Thénardier,Mistinguett,1875,1956,"actress,soundtrack,writer","tt0422758,tt0321656,tt0028184,tt0450188"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo,1989,88,Comedy,4.4,14,actor,Aga,Tuncer Sevi,1942,2012,actor,"tt0446855,tt0252562,tt0252597,tt0336004"
1043522,tt9815554,Not to Forget,Not to Forget,2021,84,Drama,6.0,10071,actress,Donna,Cloris Leachman,1926,2021,"actress,soundtrack","tt0371246,tt0072431,tt0481499,tt0067328"
1043801,tt9832110,Mooncussers,Mooncussers,1962,85,"Adventure,Biography,Drama",6.5,25,actor,Willy,Lee Aaker,1943,2021,"actor,soundtrack","tt0046906,tt0045932,tt0045883,tt0044382"
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi,1986,93,Comedy,6.4,6,actor,BaskanBeyefendi,Erol Günaydin,1933,2012,"actor,writer","tt0424619,tt0407846,tt0185027,tt0279779"
1044609,tt9883996,Dream Horse,Dream Horse,2020,113,"Biography,Comedy,Drama",6.9,5557,actress,Elsie,Lynda Baron,1939,2022,"actress,music_department,soundtrack","tt0457513,tt1685518,tt0103927,tt1182350"

In [57]:
movie_df = movie_df.drop(columns=["personagem","nomeArtista","anoNascimento","anoFalecimento","profissao","titulosMaisConhecidos","generoArtista"])

In [58]:
movie_df["genero"] = movie_df["genero"].str.split(",")
movie_df

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,[Romance],5.3,200
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,1908,120,"[Adventure, Fantasy]",5.2,66
87,tt0001285,The Life of Moses,The Life of Moses,1909,50,"[Biography, Drama, Family]",5.5,58
124,tt0001614,The Four Devils,De fire djævle,1911,60,[Drama],6.3,31
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,1913,60,[Drama],6.2,49
...,...,...,...,...,...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo,1989,88,[Comedy],4.4,14
1043522,tt9815554,Not to Forget,Not to Forget,2021,84,[Drama],6.0,10071
1043801,tt9832110,Mooncussers,Mooncussers,1962,85,"[Adventure, Biography, Drama]",6.5,25
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi,1986,93,[Comedy],6.4,6
1044609,tt9883996,Dream Horse,Dream Horse,2020,113,"[Biography, Comedy, Drama]",6.9,5557

In [59]:
dim_filme = movie_df[["id","tituloPincipal","tituloOriginal"]]
dim_filme = dim_filme.rename(columns={"id":"idImdb","tituloPincipal":"tituloPrincipal"})
dim_filme

,idImdb,tituloPrincipal,tituloOriginal
0,tt0000009,Miss Jerry,Miss Jerry
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays
87,tt0001285,The Life of Moses,The Life of Moses
124,tt0001614,The Four Devils,De fire djævle
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean
...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo
1043522,tt9815554,Not to Forget,Not to Forget
1043801,tt9832110,Mooncussers,Mooncussers
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi
1044609,tt9883996,Dream Horse,Dream Horse

In [60]:
fato_filme = movie_df[["id","anoLancamento","tempoMinutos","notaMedia","numeroVotos"]]
fato_filme = fato_filme.rename(columns={"id":"idImd"})
fato_filme

             idImd anoLancamento tempoMinutos  notaMedia  numeroVotos
0        tt0000009          1894           45        5.3          200
20       tt0000679          1908          120        5.2           66
87       tt0001285          1909           50        5.5           58
124      tt0001614          1911           60        6.3           31
136      tt0001790          1913           60        6.2           49
...            ...           ...          ...        ...          ...
1042277  tt9739386          1989           88        4.4           14
1043522  tt9815554          2021           84        6.0        10071
1043801  tt9832110          1962           85        6.5           25
1043996  tt9844738          1986           93        6.4            6
1044609  tt9883996          2020          113        6.9         5557

[51324 rows x 5 columns]

In [62]:
dim_genero= movie_df["genero"]
dim_genero = dim_genero.explode("genero")
dim_genero = dim_genero.drop_duplicates()
dim_genero

0            Romance
1          Adventure
2            Fantasy
3          Biography
4              Drama
5             Family
11           History
24               War
28            Action
30          Thriller
41             Crime
58           Mystery
61           Western
68            Horror
71            Comedy
94             Music
172           Sci-Fi
923            Sport
1772     Documentary
2674         Musical
3871       Film-Noir
5448       Animation
11594           News
55370          Adult
79755          Short
Name: genero, dtype: object

In [ ]:
df_explode = movie_df[["id","genero"]]
df_explode = df_explode.explode("genero")
df_explode= df_explode.rename(columns={"id":"idImdb"})


bridge_temp = df_explode.join(dim_filme,df_explode.id==dim_filme.idImdb)
bridge_temp2 = dim_genero.join(bridge_temp,dim_genero.id==bridge_temp.idImdb)

bridge_filmeGenero = bridge_temp2.distinct()

,idImdb,tituloPrincipal,tituloOriginal
0,tt0000009,Miss Jerry,Miss Jerry
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays
87,tt0001285,The Life of Moses,The Life of Moses
124,tt0001614,The Four Devils,De fire djævle
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean
...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo
1043522,tt9815554,Not to Forget,Not to Forget
1043801,tt9832110,Mooncussers,Mooncussers
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi
1044609,tt9883996,Dream Horse,Dream Horse