In [16]:
import pandas as pd
from sqlalchemy import create_engine
import os
from dotenv import load_dotenv
movies_csv= "movies.csv"

movie_df= pd.read_csv(movies_csv,sep="|")

movie_df

C:\Users\duduc\AppData\Local\Temp\ipykernel_13592\3720649117.py:7: DtypeWarning: Columns (0: anoLancamento) have mixed types. Specify dtype option on import or set low_memory=False.
  movie_df= pd.read_csv(movies_csv,sep="|")

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos,generoArtista,personagem,nomeArtista,anoNascimento,anoFalecimento,profissao,titulosMaisConhecidos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200,actress,Miss Geraldine Holbrook (Miss Jerry),Blanche Bayliss,1878,1951,actress,tt0000009
1,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200,actor,Mr. Hamilton,William Courtenay,1875,1933,actor,"tt0021535,tt0000009,tt0020355,tt0020403"
2,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200,actor,Chauncey Depew - the Director of the New York ...,Chauncey Depew,1834,1928,"actor,writer","tt1076833,tt0490842,tt0000009,tt4484306"
3,tt0000502,Bohemios,Bohemios,1905,100,\N,4.2,14,actor,\N,Antonio del Pozo,\N,\N,actor,tt0000502
4,tt0000502,Bohemios,Bohemios,1905,100,\N,4.2,14,actor,\N,El Mochuelo,\N,\N,actor,tt0000502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1045156,tt9916538,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,2019,123,Drama,8.3,6,actress,Dewi,Ria Irawan,1969,2020,"actress,director,writer","tt0799938,tt19246754,tt11708788,tt0353240"
1045157,tt9916730,6 Gunn,6 Gunn,2017,116,\N,8.0,8,actor,\N,Devadhar Archit,\N,\N,actor,"tt9916730,tt4292228,tt3341582"
1045158,tt9916730,6 Gunn,6 Gunn,2017,116,\N,8.0,8,actor,\N,Sunil Barve,\N,\N,"actor,music_department","tt0833441,tt1176187,tt2713666,tt12665002"
1045159,tt9916730,6 Gunn,6 Gunn,2017,116,\N,8.0,8,actor,\N,Bhushan Pradhan,\N,\N,actor,"tt4654964,tt11023422,tt11779744,tt14773818"
1045160,tt9916730,6 Gunn,6 Gunn,2017,116,\N,8.0,8,actor,Vishal,Ganesh Vasant Patil,\N,\N,"production_manager,actor","tt19868542,tt10598156"

In [17]:

movie_df = movie_df.drop_duplicates(['id'])
movie_df = movie_df[~movie_df.isin([r"\N"])]
movie_df= movie_df.dropna()
movie_df

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos,generoArtista,personagem,nomeArtista,anoNascimento,anoFalecimento,profissao,titulosMaisConhecidos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200,actress,Miss Geraldine Holbrook (Miss Jerry),Blanche Bayliss,1878,1951,actress,tt0000009
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,1908,120,"Adventure,Fantasy",5.2,66,actor,The Wizard of Oz Man,L. Frank Baum,1856,1919,"writer,producer,miscellaneous","tt0004207,tt0089908,tt0032138,tt0000679"
87,tt0001285,The Life of Moses,The Life of Moses,1909,50,"Biography,Drama,Family",5.5,58,actor,Moses,Pat Hartigan,1881,1951,"director,actor,producer","tt1308969,tt0010949,tt1320429,tt2489106"
124,tt0001614,The Four Devils,De fire djævle,1911,60,Drama,6.3,31,actor,Fritz,Robert Dinesen,1874,1972,"director,actor,writer","tt0001614,tt0473730,tt0015107,tt0129092"
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,1913,60,Drama,6.2,49,actress,Éponine Thénardier,Mistinguett,1875,1956,"actress,soundtrack,writer","tt0422758,tt0321656,tt0028184,tt0450188"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo,1989,88,Comedy,4.4,14,actor,Aga,Tuncer Sevi,1942,2012,actor,"tt0446855,tt0252562,tt0252597,tt0336004"
1043522,tt9815554,Not to Forget,Not to Forget,2021,84,Drama,6.0,10071,actress,Donna,Cloris Leachman,1926,2021,"actress,soundtrack","tt0371246,tt0072431,tt0481499,tt0067328"
1043801,tt9832110,Mooncussers,Mooncussers,1962,85,"Adventure,Biography,Drama",6.5,25,actor,Willy,Lee Aaker,1943,2021,"actor,soundtrack","tt0046906,tt0045932,tt0045883,tt0044382"
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi,1986,93,Comedy,6.4,6,actor,BaskanBeyefendi,Erol Günaydin,1933,2012,"actor,writer","tt0424619,tt0407846,tt0185027,tt0279779"
1044609,tt9883996,Dream Horse,Dream Horse,2020,113,"Biography,Comedy,Drama",6.9,5557,actress,Elsie,Lynda Baron,1939,2022,"actress,music_department,soundtrack","tt0457513,tt1685518,tt0103927,tt1182350"

In [18]:
movie_df = movie_df.drop(columns=["personagem","nomeArtista","anoNascimento","anoFalecimento","profissao","titulosMaisConhecidos","generoArtista"])
movie_df

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,1908,120,"Adventure,Fantasy",5.2,66
87,tt0001285,The Life of Moses,The Life of Moses,1909,50,"Biography,Drama,Family",5.5,58
124,tt0001614,The Four Devils,De fire djævle,1911,60,Drama,6.3,31
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,1913,60,Drama,6.2,49
...,...,...,...,...,...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo,1989,88,Comedy,4.4,14
1043522,tt9815554,Not to Forget,Not to Forget,2021,84,Drama,6.0,10071
1043801,tt9832110,Mooncussers,Mooncussers,1962,85,"Adventure,Biography,Drama",6.5,25
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi,1986,93,Comedy,6.4,6
1044609,tt9883996,Dream Horse,Dream Horse,2020,113,"Biography,Comedy,Drama",6.9,5557

In [19]:
movie_df["genero"] = movie_df["genero"].str.split(",")
movie_df

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,[Romance],5.3,200
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,1908,120,"[Adventure, Fantasy]",5.2,66
87,tt0001285,The Life of Moses,The Life of Moses,1909,50,"[Biography, Drama, Family]",5.5,58
124,tt0001614,The Four Devils,De fire djævle,1911,60,[Drama],6.3,31
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,1913,60,[Drama],6.2,49
...,...,...,...,...,...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo,1989,88,[Comedy],4.4,14
1043522,tt9815554,Not to Forget,Not to Forget,2021,84,[Drama],6.0,10071
1043801,tt9832110,Mooncussers,Mooncussers,1962,85,"[Adventure, Biography, Drama]",6.5,25
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi,1986,93,[Comedy],6.4,6
1044609,tt9883996,Dream Horse,Dream Horse,2020,113,"[Biography, Comedy, Drama]",6.9,5557

In [20]:
dim_filme = movie_df[["id","tituloPincipal","tituloOriginal"]]
dim_filme = dim_filme.rename(columns={"id":"id_imdb","tituloPincipal":"titulo_principal","tituloOriginal":"titulo_original"})
dim_filme

,id_imdb,titulo_principal,titulo_original
0,tt0000009,Miss Jerry,Miss Jerry
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays
87,tt0001285,The Life of Moses,The Life of Moses
124,tt0001614,The Four Devils,De fire djævle
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean
...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo
1043522,tt9815554,Not to Forget,Not to Forget
1043801,tt9832110,Mooncussers,Mooncussers
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi
1044609,tt9883996,Dream Horse,Dream Horse

In [21]:
fato_filme = movie_df[["id","anoLancamento","tempoMinutos","notaMedia","numeroVotos"]]
fato_filme = fato_filme.rename(columns={"id":"id_imdb","anoLancamento":"ano_lancamento","tempoMinutos":"tempo_minutos","notaMedia":"nota_media","numeroVotos":"numero_votos"})
fato_filme

           id_imdb ano_lancamento tempo_minutos  nota_media  numero_votos
0        tt0000009           1894            45         5.3           200
20       tt0000679           1908           120         5.2            66
87       tt0001285           1909            50         5.5            58
124      tt0001614           1911            60         6.3            31
136      tt0001790           1913            60         6.2            49
...            ...            ...           ...         ...           ...
1042277  tt9739386           1989            88         4.4            14
1043522  tt9815554           2021            84         6.0         10071
1043801  tt9832110           1962            85         6.5            25
1043996  tt9844738           1986            93         6.4             6
1044609  tt9883996           2020           113         6.9          5557

[51324 rows x 5 columns]

In [22]:
dim_genero= movie_df["genero"]
dim_genero = dim_genero.explode("genero")
dim_genero = dim_genero.rename("nome")
dim_genero = dim_genero.drop_duplicates()
dim_genero = pd.DataFrame(dim_genero)
dim_genero["id"]= range(len(dim_genero))
dim_genero

              nome  id
0          Romance   0
1        Adventure   1
2          Fantasy   2
3        Biography   3
4            Drama   4
5           Family   5
11         History   6
24             War   7
28          Action   8
30        Thriller   9
41           Crime  10
58         Mystery  11
61         Western  12
68          Horror  13
71          Comedy  14
94           Music  15
172         Sci-Fi  16
923          Sport  17
1772   Documentary  18
2674       Musical  19
3871     Film-Noir  20
5448     Animation  21
11594         News  22
55370        Adult  23
79755        Short  24

In [23]:
df_explode = movie_df[["id","genero"]]
df_explode = df_explode.explode("genero")
df_explode= df_explode.rename(columns={"id":"id_imdb","genero":"nome"})

dim_filme["id_imdb"]= dim_filme.id_imdb.astype("str")
df_explode["id_imdb"] = df_explode.id_imdb.astype("str")
df_bridge = df_explode.merge(dim_genero,on="nome",how="inner")
df_bridge= df_bridge.rename(columns={"id":"id_genero"})

df_bridge

         id_imdb       nome  id_genero
0      tt0000009    Romance          0
1      tt0000679  Adventure          1
2      tt0000679    Fantasy          2
3      tt0001285  Biography          3
4      tt0001285      Drama          4
...          ...        ...        ...
95326  tt9832110      Drama          4
95327  tt9844738     Comedy         14
95328  tt9883996  Biography          3
95329  tt9883996     Comedy         14
95330  tt9883996      Drama          4

[95331 rows x 3 columns]

In [24]:
load_dotenv()
DB_SENHA=os.getenv("DB_SENHA")
db = create_engine('postgresql://eduar:{DB_SENHA}@localhost:5432/DW_Filmes')

In [25]:
dim_genero = dim_genero[["nome"]]

In [26]:
dim_genero.to_sql("dim_genero",
                  con=db,
                  if_exists="delete_rows",
                  index=False)
dim_filme.to_sql("dim_filme",
                  con=db,
                  if_exists="delete_rows",
                  index=False)

324

In [27]:
pd.read_sql("select * from dim_filme limit 10",db)

,sk_filme,id_imdb,titulo_principal,titulo_original
0,51325,tt0000009,Miss Jerry,Miss Jerry
1,51326,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays
2,51327,tt0001285,The Life of Moses,The Life of Moses
3,51328,tt0001614,The Four Devils,De fire djævle
4,51329,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean
5,51330,tt0001812,Oedipus Rex,Oedipus Rex
6,51331,tt0001911,Nell Gwynne,Sweet Nell of Old Drury
7,51332,tt0001964,The Traitress,Die Verräterin
8,51333,tt0002101,Cleopatra,Cleopatra
9,51334,tt0002130,Dante's Inferno,L'Inferno

In [28]:
pd.read_sql("SELECT * FROM dim_genero limit 10",db)

   sk_genero       nome
0         26    Romance
1         27  Adventure
2         28    Fantasy
3         29  Biography
4         30      Drama
5         31     Family
6         32    History
7         33        War
8         34     Action
9         35   Thriller

In [29]:
df_bridge.to_sql("bridge_filme_genero",
                 con=db,
                 if_exists="replace",
                 index=False)

pd.read_sql("select * from bridge_filme_genero limit 10",db)

     id_imdb       nome  id_genero
0  tt0000009    Romance          0
1  tt0000679  Adventure          1
2  tt0000679    Fantasy          2
3  tt0001285  Biography          3
4  tt0001285      Drama          4
5  tt0001285     Family          5
6  tt0001614      Drama          4
7  tt0001790      Drama          4
8  tt0001812      Drama          4
9  tt0001911  Biography          3

In [30]:
query = "SELECT dim_genero.sk_genero, dim_filme.sk_filme FROM bridge_filme_genero INNER JOIN dim_filme ON bridge_filme_genero.id_imdb = dim_filme.id_imdb INNER JOIN dim_genero ON bridge_filme_genero.nome = dim_genero.nome"
df_bridge = pd.read_sql(query,db)
df_bridge.to_sql("bridge_filme_genero",
                 con=db,
                 if_exists="replace",
                 index=False)
pd.read_sql("select * from bridge_filme_genero limit 10",db)

   sk_genero  sk_filme
0         26     51325
1         27     51326
2         28     51326
3         29     51327
4         30     51327
5         31     51327
6         30     51328
7         30     51329
8         30     51330
9         29     51331