In [45]:
import pandas as pd
from sqlalchemy import create_engine
import os
from dotenv import load_dotenv
movies_csv= "movies.csv"

movie_df= pd.read_csv(movies_csv,sep="|")

movie_df

C:\Users\duduc\AppData\Local\Temp\ipykernel_12580\3720649117.py:7: DtypeWarning: Columns (0: anoLancamento) have mixed types. Specify dtype option on import or set low_memory=False.
  movie_df= pd.read_csv(movies_csv,sep="|")

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos,generoArtista,personagem,nomeArtista,anoNascimento,anoFalecimento,profissao,titulosMaisConhecidos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200,actress,Miss Geraldine Holbrook (Miss Jerry),Blanche Bayliss,1878,1951,actress,tt0000009
1,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200,actor,Mr. Hamilton,William Courtenay,1875,1933,actor,"tt0021535,tt0000009,tt0020355,tt0020403"
2,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200,actor,Chauncey Depew - the Director of the New York ...,Chauncey Depew,1834,1928,"actor,writer","tt1076833,tt0490842,tt0000009,tt4484306"
3,tt0000502,Bohemios,Bohemios,1905,100,\N,4.2,14,actor,\N,Antonio del Pozo,\N,\N,actor,tt0000502
4,tt0000502,Bohemios,Bohemios,1905,100,\N,4.2,14,actor,\N,El Mochuelo,\N,\N,actor,tt0000502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1045156,tt9916538,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,2019,123,Drama,8.3,6,actress,Dewi,Ria Irawan,1969,2020,"actress,director,writer","tt0799938,tt19246754,tt11708788,tt0353240"
1045157,tt9916730,6 Gunn,6 Gunn,2017,116,\N,8.0,8,actor,\N,Devadhar Archit,\N,\N,actor,"tt9916730,tt4292228,tt3341582"
1045158,tt9916730,6 Gunn,6 Gunn,2017,116,\N,8.0,8,actor,\N,Sunil Barve,\N,\N,"actor,music_department","tt0833441,tt1176187,tt2713666,tt12665002"
1045159,tt9916730,6 Gunn,6 Gunn,2017,116,\N,8.0,8,actor,\N,Bhushan Pradhan,\N,\N,actor,"tt4654964,tt11023422,tt11779744,tt14773818"
1045160,tt9916730,6 Gunn,6 Gunn,2017,116,\N,8.0,8,actor,Vishal,Ganesh Vasant Patil,\N,\N,"production_manager,actor","tt19868542,tt10598156"

In [46]:

movie_df = movie_df.drop_duplicates(['id'])
movie_df = movie_df[~movie_df.isin([r"\N"])]
movie_df= movie_df.dropna()
movie_df

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos,generoArtista,personagem,nomeArtista,anoNascimento,anoFalecimento,profissao,titulosMaisConhecidos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200,actress,Miss Geraldine Holbrook (Miss Jerry),Blanche Bayliss,1878,1951,actress,tt0000009
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,1908,120,"Adventure,Fantasy",5.2,66,actor,The Wizard of Oz Man,L. Frank Baum,1856,1919,"writer,producer,miscellaneous","tt0004207,tt0089908,tt0032138,tt0000679"
87,tt0001285,The Life of Moses,The Life of Moses,1909,50,"Biography,Drama,Family",5.5,58,actor,Moses,Pat Hartigan,1881,1951,"director,actor,producer","tt1308969,tt0010949,tt1320429,tt2489106"
124,tt0001614,The Four Devils,De fire djævle,1911,60,Drama,6.3,31,actor,Fritz,Robert Dinesen,1874,1972,"director,actor,writer","tt0001614,tt0473730,tt0015107,tt0129092"
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,1913,60,Drama,6.2,49,actress,Éponine Thénardier,Mistinguett,1875,1956,"actress,soundtrack,writer","tt0422758,tt0321656,tt0028184,tt0450188"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo,1989,88,Comedy,4.4,14,actor,Aga,Tuncer Sevi,1942,2012,actor,"tt0446855,tt0252562,tt0252597,tt0336004"
1043522,tt9815554,Not to Forget,Not to Forget,2021,84,Drama,6.0,10071,actress,Donna,Cloris Leachman,1926,2021,"actress,soundtrack","tt0371246,tt0072431,tt0481499,tt0067328"
1043801,tt9832110,Mooncussers,Mooncussers,1962,85,"Adventure,Biography,Drama",6.5,25,actor,Willy,Lee Aaker,1943,2021,"actor,soundtrack","tt0046906,tt0045932,tt0045883,tt0044382"
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi,1986,93,Comedy,6.4,6,actor,BaskanBeyefendi,Erol Günaydin,1933,2012,"actor,writer","tt0424619,tt0407846,tt0185027,tt0279779"
1044609,tt9883996,Dream Horse,Dream Horse,2020,113,"Biography,Comedy,Drama",6.9,5557,actress,Elsie,Lynda Baron,1939,2022,"actress,music_department,soundtrack","tt0457513,tt1685518,tt0103927,tt1182350"

In [47]:
movie_df = movie_df.drop(columns=["personagem","nomeArtista","anoNascimento","anoFalecimento","profissao","titulosMaisConhecidos","generoArtista"])
movie_df

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,1908,120,"Adventure,Fantasy",5.2,66
87,tt0001285,The Life of Moses,The Life of Moses,1909,50,"Biography,Drama,Family",5.5,58
124,tt0001614,The Four Devils,De fire djævle,1911,60,Drama,6.3,31
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,1913,60,Drama,6.2,49
...,...,...,...,...,...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo,1989,88,Comedy,4.4,14
1043522,tt9815554,Not to Forget,Not to Forget,2021,84,Drama,6.0,10071
1043801,tt9832110,Mooncussers,Mooncussers,1962,85,"Adventure,Biography,Drama",6.5,25
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi,1986,93,Comedy,6.4,6
1044609,tt9883996,Dream Horse,Dream Horse,2020,113,"Biography,Comedy,Drama",6.9,5557

In [48]:
movie_df["genero"] = movie_df["genero"].str.split(",")
movie_df

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,[Romance],5.3,200
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,1908,120,"[Adventure, Fantasy]",5.2,66
87,tt0001285,The Life of Moses,The Life of Moses,1909,50,"[Biography, Drama, Family]",5.5,58
124,tt0001614,The Four Devils,De fire djævle,1911,60,[Drama],6.3,31
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,1913,60,[Drama],6.2,49
...,...,...,...,...,...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo,1989,88,[Comedy],4.4,14
1043522,tt9815554,Not to Forget,Not to Forget,2021,84,[Drama],6.0,10071
1043801,tt9832110,Mooncussers,Mooncussers,1962,85,"[Adventure, Biography, Drama]",6.5,25
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi,1986,93,[Comedy],6.4,6
1044609,tt9883996,Dream Horse,Dream Horse,2020,113,"[Biography, Comedy, Drama]",6.9,5557

In [49]:
movie_df = movie_df.rename(columns={"id":"id_imdb","tituloPincipal":"titulo_principal","tituloOriginal":"titulo_original","notaMedia":"nota_media","numeroVotos":"numero_votos","tempoMinutos":"tempo_minutos"})
movie_df = movie_df[movie_df["numero_votos"] > 1000]
movie_df

,id_imdb,titulo_principal,titulo_original,anoLancamento,tempo_minutos,genero,nota_media,numero_votos
187,tt0002130,Dante's Inferno,L'Inferno,1911,71,"[Adventure, Drama, Fantasy]",7.0,2993
328,tt0002844,Fantômas: In the Shadow of the Guillotine,Fantômas - À l'ombre de la guillotine,1913,54,"[Crime, Drama]",6.9,2330
373,tt0003014,Ingeborg Holm,Ingeborg Holm,1913,96,[Drama],7.0,1252
390,tt0003037,Fantomas: The Man in Black,Juve contre Fantômas,1913,61,"[Crime, Drama]",6.9,1585
412,tt0003165,Fantômas: The Dead Man Who Killed,Le mort qui tue,1913,90,"[Crime, Drama, Mystery]",6.9,1252
...,...,...,...,...,...,...,...,...
1034633,tt9260636,Bigil,Bigil,2019,179,"[Action, Drama, Sport]",6.7,21411
1039522,tt9577852,Rolling Thunder Revue,Rolling Thunder Revue: A Bob Dylan Story by Ma...,2019,142,"[Biography, Documentary, History]",7.6,6937
1041644,tt9695258,So My Grandma's a Lesbian!,Salir del ropero,2019,94,[Comedy],4.4,1245
1043522,tt9815554,Not to Forget,Not to Forget,2021,84,[Drama],6.0,10071
1044609,tt9883996,Dream Horse,Dream Horse,2020,113,"[Biography, Comedy, Drama]",6.9,5557

In [50]:
dim_filme = movie_df[["id_imdb","titulo_principal","titulo_original"]]
dim_filme

,id_imdb,titulo_principal,titulo_original
187,tt0002130,Dante's Inferno,L'Inferno
328,tt0002844,Fantômas: In the Shadow of the Guillotine,Fantômas - À l'ombre de la guillotine
373,tt0003014,Ingeborg Holm,Ingeborg Holm
390,tt0003037,Fantomas: The Man in Black,Juve contre Fantômas
412,tt0003165,Fantômas: The Dead Man Who Killed,Le mort qui tue
...,...,...,...
1034633,tt9260636,Bigil,Bigil
1039522,tt9577852,Rolling Thunder Revue,Rolling Thunder Revue: A Bob Dylan Story by Ma...
1041644,tt9695258,So My Grandma's a Lesbian!,Salir del ropero
1043522,tt9815554,Not to Forget,Not to Forget
1044609,tt9883996,Dream Horse,Dream Horse

In [51]:
dim_genero= movie_df["genero"]
dim_genero = dim_genero.explode("genero")
dim_genero = dim_genero.rename("nome")
dim_genero = dim_genero.drop_duplicates()
dim_genero = pd.DataFrame(dim_genero)
dim_genero["id"]= range(len(dim_genero))
dim_genero

              nome  id
0        Adventure   0
1            Drama   1
2          Fantasy   2
3            Crime   3
10         Mystery   4
13          Horror   5
19         History   6
28          Action   7
31          Comedy   8
33             War   9
36         Romance  10
37       Biography  11
45          Sci-Fi  12
52          Family  13
80        Thriller  14
87         Western  15
159          Sport  16
169    Documentary  17
282        Musical  18
368          Music  19
402      Film-Noir  20
573      Animation  21
11147        Adult  22
17418         News  23

In [52]:
df_explode = movie_df[["id_imdb","genero"]]
df_explode = df_explode.explode("genero")
df_explode= df_explode.rename(columns={"id":"id_imdb","genero":"nome"})

dim_filme["id_imdb"]= dim_filme.id_imdb.astype("str")
df_explode["id_imdb"] = df_explode.id_imdb.astype("str")
df_bridge = df_explode.merge(dim_genero,on="nome",how="inner")
df_bridge= df_bridge.rename(columns={"id":"id_genero"})

df_bridge

         id_imdb       nome  id_genero
0      tt0002130  Adventure          0
1      tt0002130      Drama          1
2      tt0002130    Fantasy          2
3      tt0002844      Crime          3
4      tt0002844      Drama          1
...          ...        ...        ...
17903  tt9695258     Comedy          8
17904  tt9815554      Drama          1
17905  tt9883996  Biography         11
17906  tt9883996     Comedy          8
17907  tt9883996      Drama          1

[17908 rows x 3 columns]

In [53]:
load_dotenv()
DB_SENHA=os.getenv("DB_SENHA")
db = create_engine('postgresql://eduar:{DB_SENHA}@localhost:5432/DW_Filmes')

In [54]:
dim_genero = dim_genero[["nome"]]

In [55]:
dim_genero.to_sql("dim_genero",
                  con=db,
                  if_exists="delete_rows",
                  index=False)
dim_filme.to_sql("dim_filme",
                  con=db,
                  if_exists="delete_rows",
                  index=False)

566

In [56]:
pd.read_sql("select * from dim_filme limit 10",db)

,sk_filme,id_imdb,titulo_principal,titulo_original
0,256621,tt0002130,Dante's Inferno,L'Inferno
1,256622,tt0002844,Fantômas: In the Shadow of the Guillotine,Fantômas - À l'ombre de la guillotine
2,256623,tt0003014,Ingeborg Holm,Ingeborg Holm
3,256624,tt0003037,Fantomas: The Man in Black,Juve contre Fantômas
4,256625,tt0003165,Fantômas: The Dead Man Who Killed,Le mort qui tue
5,256626,tt0003419,The Student of Prague,Der Student von Prag
6,256627,tt0003643,The Avenging Conscience: or 'Thou Shalt Not Kill',The Avenging Conscience: or 'Thou Shalt Not Kill'
7,256628,tt0003740,Cabiria,Cabiria
8,256629,tt0003772,Cinderella,Cinderella
9,256630,tt0003930,Fantomas: The Mysterious Finger Print,Fantômas contre Fantômas

In [57]:
pd.read_sql("SELECT * FROM dim_genero limit 10",db)

   sk_genero       nome
0        126  Adventure
1        127      Drama
2        128    Fantasy
3        129      Crime
4        130    Mystery
5        131     Horror
6        132    History
7        133     Action
8        134     Comedy
9        135        War

In [58]:
df_bridge.to_sql("bridge_filme_genero",
                 con=db,
                 if_exists="replace",
                 index=False)

pd.read_sql("select * from bridge_filme_genero limit 10",db)

     id_imdb       nome  id_genero
0  tt0002130  Adventure          0
1  tt0002130      Drama          1
2  tt0002130    Fantasy          2
3  tt0002844      Crime          3
4  tt0002844      Drama          1
5  tt0003014      Drama          1
6  tt0003037      Crime          3
7  tt0003037      Drama          1
8  tt0003165      Crime          3
9  tt0003165      Drama          1

In [59]:
query = "SELECT dim_genero.sk_genero, dim_filme.sk_filme FROM bridge_filme_genero INNER JOIN dim_filme ON bridge_filme_genero.id_imdb = dim_filme.id_imdb INNER JOIN dim_genero ON bridge_filme_genero.nome = dim_genero.nome"
df_bridge = pd.read_sql(query,db)
df_bridge.to_sql("bridge_filme_genero",
                 con=db,
                 if_exists="replace",
                 index=False)
pd.read_sql("select * from bridge_filme_genero limit 10",db)

   sk_genero  sk_filme
0        126    256621
1        127    256621
2        128    256621
3        129    256622
4        127    256622
5        127    256623
6        129    256624
7        127    256624
8        129    256625
9        127    256625

In [60]:
movie_df.to_sql("tabela_aux",
                con=db,
                if_exists="replace",
                index=False)

566