In [ ]:
import pandas as pd
from sqlalchemy import create_engine
import os
from dotenv import load_dotenv
movies_csv= "movies.csv"

movie_df= pd.read_csv(movies_csv,sep="|")

movie_df

C:\Users\duduc\AppData\Local\Temp\ipykernel_9328\4218373251.py:6: DtypeWarning: Columns (0: anoLancamento) have mixed types. Specify dtype option on import or set low_memory=False.
  movie_df= pd.read_csv(movies_csv,sep="|")

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos,generoArtista,personagem,nomeArtista,anoNascimento,anoFalecimento,profissao,titulosMaisConhecidos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200,actress,Miss Geraldine Holbrook (Miss Jerry),Blanche Bayliss,1878,1951,actress,tt0000009
1,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200,actor,Mr. Hamilton,William Courtenay,1875,1933,actor,"tt0021535,tt0000009,tt0020355,tt0020403"
2,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200,actor,Chauncey Depew - the Director of the New York ...,Chauncey Depew,1834,1928,"actor,writer","tt1076833,tt0490842,tt0000009,tt4484306"
3,tt0000502,Bohemios,Bohemios,1905,100,\N,4.2,14,actor,\N,Antonio del Pozo,\N,\N,actor,tt0000502
4,tt0000502,Bohemios,Bohemios,1905,100,\N,4.2,14,actor,\N,El Mochuelo,\N,\N,actor,tt0000502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1045156,tt9916538,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,2019,123,Drama,8.3,6,actress,Dewi,Ria Irawan,1969,2020,"actress,director,writer","tt0799938,tt19246754,tt11708788,tt0353240"
1045157,tt9916730,6 Gunn,6 Gunn,2017,116,\N,8.0,8,actor,\N,Devadhar Archit,\N,\N,actor,"tt9916730,tt4292228,tt3341582"
1045158,tt9916730,6 Gunn,6 Gunn,2017,116,\N,8.0,8,actor,\N,Sunil Barve,\N,\N,"actor,music_department","tt0833441,tt1176187,tt2713666,tt12665002"
1045159,tt9916730,6 Gunn,6 Gunn,2017,116,\N,8.0,8,actor,\N,Bhushan Pradhan,\N,\N,actor,"tt4654964,tt11023422,tt11779744,tt14773818"
1045160,tt9916730,6 Gunn,6 Gunn,2017,116,\N,8.0,8,actor,Vishal,Ganesh Vasant Patil,\N,\N,"production_manager,actor","tt19868542,tt10598156"

In [58]:

movie_df = movie_df.drop_duplicates(['id'])
movie_df = movie_df[~movie_df.isin([r"\N"])]
movie_df= movie_df.dropna()
movie_df

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos,generoArtista,personagem,nomeArtista,anoNascimento,anoFalecimento,profissao,titulosMaisConhecidos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200,actress,Miss Geraldine Holbrook (Miss Jerry),Blanche Bayliss,1878,1951,actress,tt0000009
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,1908,120,"Adventure,Fantasy",5.2,66,actor,The Wizard of Oz Man,L. Frank Baum,1856,1919,"writer,producer,miscellaneous","tt0004207,tt0089908,tt0032138,tt0000679"
87,tt0001285,The Life of Moses,The Life of Moses,1909,50,"Biography,Drama,Family",5.5,58,actor,Moses,Pat Hartigan,1881,1951,"director,actor,producer","tt1308969,tt0010949,tt1320429,tt2489106"
124,tt0001614,The Four Devils,De fire djævle,1911,60,Drama,6.3,31,actor,Fritz,Robert Dinesen,1874,1972,"director,actor,writer","tt0001614,tt0473730,tt0015107,tt0129092"
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,1913,60,Drama,6.2,49,actress,Éponine Thénardier,Mistinguett,1875,1956,"actress,soundtrack,writer","tt0422758,tt0321656,tt0028184,tt0450188"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo,1989,88,Comedy,4.4,14,actor,Aga,Tuncer Sevi,1942,2012,actor,"tt0446855,tt0252562,tt0252597,tt0336004"
1043522,tt9815554,Not to Forget,Not to Forget,2021,84,Drama,6.0,10071,actress,Donna,Cloris Leachman,1926,2021,"actress,soundtrack","tt0371246,tt0072431,tt0481499,tt0067328"
1043801,tt9832110,Mooncussers,Mooncussers,1962,85,"Adventure,Biography,Drama",6.5,25,actor,Willy,Lee Aaker,1943,2021,"actor,soundtrack","tt0046906,tt0045932,tt0045883,tt0044382"
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi,1986,93,Comedy,6.4,6,actor,BaskanBeyefendi,Erol Günaydin,1933,2012,"actor,writer","tt0424619,tt0407846,tt0185027,tt0279779"
1044609,tt9883996,Dream Horse,Dream Horse,2020,113,"Biography,Comedy,Drama",6.9,5557,actress,Elsie,Lynda Baron,1939,2022,"actress,music_department,soundtrack","tt0457513,tt1685518,tt0103927,tt1182350"

In [59]:
movie_df = movie_df.drop(columns=["personagem","nomeArtista","anoNascimento","anoFalecimento","profissao","titulosMaisConhecidos","generoArtista"])
movie_df

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,Romance,5.3,200
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,1908,120,"Adventure,Fantasy",5.2,66
87,tt0001285,The Life of Moses,The Life of Moses,1909,50,"Biography,Drama,Family",5.5,58
124,tt0001614,The Four Devils,De fire djævle,1911,60,Drama,6.3,31
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,1913,60,Drama,6.2,49
...,...,...,...,...,...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo,1989,88,Comedy,4.4,14
1043522,tt9815554,Not to Forget,Not to Forget,2021,84,Drama,6.0,10071
1043801,tt9832110,Mooncussers,Mooncussers,1962,85,"Adventure,Biography,Drama",6.5,25
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi,1986,93,Comedy,6.4,6
1044609,tt9883996,Dream Horse,Dream Horse,2020,113,"Biography,Comedy,Drama",6.9,5557

In [60]:
movie_df["genero"] = movie_df["genero"].str.split(",")
movie_df

,id,tituloPincipal,tituloOriginal,anoLancamento,tempoMinutos,genero,notaMedia,numeroVotos
0,tt0000009,Miss Jerry,Miss Jerry,1894,45,[Romance],5.3,200
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,1908,120,"[Adventure, Fantasy]",5.2,66
87,tt0001285,The Life of Moses,The Life of Moses,1909,50,"[Biography, Drama, Family]",5.5,58
124,tt0001614,The Four Devils,De fire djævle,1911,60,[Drama],6.3,31
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,1913,60,[Drama],6.2,49
...,...,...,...,...,...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo,1989,88,[Comedy],4.4,14
1043522,tt9815554,Not to Forget,Not to Forget,2021,84,[Drama],6.0,10071
1043801,tt9832110,Mooncussers,Mooncussers,1962,85,"[Adventure, Biography, Drama]",6.5,25
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi,1986,93,[Comedy],6.4,6
1044609,tt9883996,Dream Horse,Dream Horse,2020,113,"[Biography, Comedy, Drama]",6.9,5557

In [61]:
dim_filme = movie_df[["id","tituloPincipal","tituloOriginal"]]
dim_filme = dim_filme.rename(columns={"id":"id_imdb","tituloPincipal":"titulo_principal","tituloOriginal":"titulo_original"})
dim_filme

,id_imdb,titulo_principal,titulo_original
0,tt0000009,Miss Jerry,Miss Jerry
20,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays
87,tt0001285,The Life of Moses,The Life of Moses
124,tt0001614,The Four Devils,De fire djævle
136,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean
...,...,...,...
1042277,tt9739386,Kinali Hanzo,Kinali Hanzo
1043522,tt9815554,Not to Forget,Not to Forget
1043801,tt9832110,Mooncussers,Mooncussers
1043996,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi
1044609,tt9883996,Dream Horse,Dream Horse

In [62]:
fato_filme = movie_df[["id","anoLancamento","tempoMinutos","notaMedia","numeroVotos"]]
fato_filme = fato_filme.rename(columns={"id":"id_imdb","anoLancamento":"ano_lancamento","tempoMinutos":"tempo_minutos","notaMedia":"nota_media","numeroVotos":"numero_votos"})
fato_filme

           id_imdb ano_lancamento tempo_minutos  nota_media  numero_votos
0        tt0000009           1894            45         5.3           200
20       tt0000679           1908           120         5.2            66
87       tt0001285           1909            50         5.5            58
124      tt0001614           1911            60         6.3            31
136      tt0001790           1913            60         6.2            49
...            ...            ...           ...         ...           ...
1042277  tt9739386           1989            88         4.4            14
1043522  tt9815554           2021            84         6.0         10071
1043801  tt9832110           1962            85         6.5            25
1043996  tt9844738           1986            93         6.4             6
1044609  tt9883996           2020           113         6.9          5557

[51324 rows x 5 columns]

In [63]:
dim_genero= movie_df["genero"]
dim_genero = dim_genero.explode("genero")
dim_genero = dim_genero.rename("nome")
dim_genero = dim_genero.drop_duplicates()
dim_genero

0            Romance
1          Adventure
2            Fantasy
3          Biography
4              Drama
5             Family
11           History
24               War
28            Action
30          Thriller
41             Crime
58           Mystery
61           Western
68            Horror
71            Comedy
94             Music
172           Sci-Fi
923            Sport
1772     Documentary
2674         Musical
3871       Film-Noir
5448       Animation
11594           News
55370          Adult
79755          Short
Name: nome, dtype: str

In [64]:
df_explode = movie_df[["id","genero"]]
df_explode = df_explode.explode("genero")
df_explode= df_explode.rename(columns={"id":"id_imdb"})

dim_filme["id_imdb"]= dim_filme.id_imdb.astype("str")
df_explode["id_imdb"] = df_explode.id_imdb.astype("str")


bridge_temp = pd.merge(df_explode,dim_filme,on="id_imdb", how="inner")

bridge_temp

,id_imdb,genero,titulo_principal,titulo_original
0,tt0000009,Romance,Miss Jerry,Miss Jerry
1,tt0000679,Adventure,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays
2,tt0000679,Fantasy,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays
3,tt0001285,Biography,The Life of Moses,The Life of Moses
4,tt0001285,Drama,The Life of Moses,The Life of Moses
...,...,...,...,...
95326,tt9832110,Drama,Mooncussers,Mooncussers
95327,tt9844738,Comedy,Kocamin Nisanlisi,Kocamin Nisanlisi
95328,tt9883996,Biography,Dream Horse,Dream Horse
95329,tt9883996,Comedy,Dream Horse,Dream Horse
95330,tt9883996,Drama,Dream Horse,Dream Horse

In [65]:

bridge_filmeGenero = bridge_temp[["id_imdb","genero"]]
bridge_filmeGenero = bridge_filmeGenero.drop_duplicates()
bridge_filmeGenero

         id_imdb     genero
0      tt0000009    Romance
1      tt0000679  Adventure
2      tt0000679    Fantasy
3      tt0001285  Biography
4      tt0001285      Drama
...          ...        ...
95326  tt9832110      Drama
95327  tt9844738     Comedy
95328  tt9883996  Biography
95329  tt9883996     Comedy
95330  tt9883996      Drama

[95331 rows x 2 columns]

In [ ]:
load_dotenv()
DB_SENHA=os.getenv("DB_SENHA")
db = create_engine('postgresql://postgres:{DB_SENHA}@localhost:5432/DataWarehouse_Filmes')

In [67]:
query = "SELECT * FROM fato_filme"
consulta = pd.read_sql(query,db)
consulta

Empty DataFrame
Columns: [sk_filme, sk_data_lancamento, nota_media, numero_votos, tempo_minutos]
Index: []

In [68]:
dim_genero.to_sql(
    name="dim_genero",
    con=db,
    if_exists="append",
    index=False
)

DatabaseError: Execution failed on sql 'INSERT INTO dim_genero (nome) VALUES (:nome)': (psycopg2.errors.UniqueViolation) ERRO:  duplicar valor da chave viola a restrição de unicidade "dim_genero_nome_key"
DETAIL:  Chave (nome)=(Romance) já existe.

[SQL: INSERT INTO dim_genero (nome) VALUES (%(nome__0)s), (%(nome__1)s), (%(nome__2)s), (%(nome__3)s), (%(nome__4)s), (%(nome__5)s), (%(nome__6)s), (%(nome__7)s), (%(nome__8)s), (%(nome__9)s), (%(nome__10)s), (%(nome__11)s), (%(nome__12)s), (%(nome__13)s), (%(nome__14)s), (%(nome__15)s), (%(nome__16)s), (%(nome__17)s), (%(nome__18)s), (%(nome__19)s), (%(nome__20)s), (%(nome__21)s), (%(nome__22)s), (%(nome__23)s), (%(nome__24)s)]
[parameters: {'nome__0': 'Romance', 'nome__1': 'Adventure', 'nome__2': 'Fantasy', 'nome__3': 'Biography', 'nome__4': 'Drama', 'nome__5': 'Family', 'nome__6': 'History', 'nome__7': 'War', 'nome__8': 'Action', 'nome__9': 'Thriller', 'nome__10': 'Crime', 'nome__11': 'Mystery', 'nome__12': 'Western', 'nome__13': 'Horror', 'nome__14': 'Comedy', 'nome__15': 'Music', 'nome__16': 'Sci-Fi', 'nome__17': 'Sport', 'nome__18': 'Documentary', 'nome__19': 'Musical', 'nome__20': 'Film-Noir', 'nome__21': 'Animation', 'nome__22': 'News', 'nome__23': 'Adult', 'nome__24': 'Short'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [ ]:
pd.read_sql("SELECT * FROM dim_genero",db)

    sk_genero         nome
0           1      Romance
1           2    Adventure
2           3      Fantasy
3           4    Biography
4           5        Drama
5           6       Family
6           7      History
7           8          War
8           9       Action
9          10     Thriller
10         11        Crime
11         12      Mystery
12         13      Western
13         14       Horror
14         15       Comedy
15         16        Music
16         17       Sci-Fi
17         18        Sport
18         19  Documentary
19         20      Musical
20         21    Film-Noir
21         22    Animation
22         23         News
23         24        Adult
24         25        Short

In [ ]:
dim_filme.to_sql(
    name="dim_filme",
    con=db,
    if_exists="append",
    index=False)

324

In [ ]:
pd.read_sql("SELECT * FROM dim_filme",db)

,sk_filme,id_imdb,titulo_principal,titulo_original
0,1,tt0000009,Miss Jerry,Miss Jerry
1,2,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays
2,3,tt0001285,The Life of Moses,The Life of Moses
3,4,tt0001614,The Four Devils,De fire djævle
4,5,tt0001790,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean
...,...,...,...,...
51319,51320,tt9739386,Kinali Hanzo,Kinali Hanzo
51320,51321,tt9815554,Not to Forget,Not to Forget
51321,51322,tt9832110,Mooncussers,Mooncussers
51322,51323,tt9844738,Kocamin Nisanlisi,Kocamin Nisanlisi
51323,51324,tt9883996,Dream Horse,Dream Horse